version: '3.1'

services:

  events-db:
    image: hub.docker.prod.walmart.com/library/mariadb
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: "events"

#  eventspring:
#    image: events
#    depends_on:
#      - events-db
#    ports:
#      - 80:8080
#    environment:
#      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
#      SPRING_DATASOURCE_URL: "jdbc:mysql://events-db/events?useSSL=false"

  events:
    image: eventsnet
    depends_on:
    - events-db
    ports:
    - 80:8000
    environment:
      MYSQLCONNSTR_DefaultConnection: "server=events-db;database=events;user=${DATABASE_USER};password=${DATABASE_PASSWORD}"

